version: '3.8'
services:
  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links: 
      - redis
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: development
  
  redis:
    image: redis
    ports:
      - "6379:6379"
